apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: vaibhavnitor/backend-22:latest
        ports:
        - containerPort: 81
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__Database
          value: "Server=dbinstance.cnk0u26aswzz.us-east-1.rds.amazonaws.com,1433;Database=dbinstsnce;User Id=sdmin;Password=vaibhavchavan;"
        - name: jwtConfig__Key
          value: "Bhaskarmehtajharkhand"
        - name: jwtConfig__Duration
          value: "1"

