apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  ConnectionStrings__Database: <base64-encoded-connection-string>
  jwtConfig__Key: <base64-encoded-jwt-key>
  jwtConfig__Duration: <base64-encoded-jwt-duration>
