apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  ConnectionStrings__Database: dbinstance.cnk0u26aswzz.us-east-1.rds.amazonaws.com
  jwtConfig__Key: YWRtaW4=
  jwtConfig__Duration: dmFpYmhhdmNoYXZhbg==
