apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  ConnectionStrings__Database: <base64_encoded_connection_string>
  jwtConfig__Key: <base64_encoded_jwt_key>
  jwtConfig__Duration: <base64_encoded_jwt_duration>
