apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  ConnectionStrings__Database: ZGF0YWJhc2UxLmNuazB1MjZhc3d6ei51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20= #database1.cnk0u26aswzz.us-east-1.rds.amazonaws.com
  jwtConfig__Key: YWRtaW4=
  jwtConfig__Duration: dmFpYmhhdmNoYXZhbg==
